#!/bin/bash

rm -rf ~/.zshrc \
       ~/.gitconfig \
       ~/.ssh/config \
       ~/.gitignore_global \
       ~/.gitcommit_template

ln -s ~/dotfiles/zsh/zshrc ~/.zshrc
ln -s ~/dotfiles/gitconfig ~/.gitconfig
ln -s ~/dotfiles/gitignore_global ~/.gitignore_global

mkdir -p ~/.ssh
mkdir -p ~/code

cat ~/dotfiles/sshconfig > ~/.ssh/config

OH_MY_ZSH=~/dotfiles/oh-my-zsh
git clone https://github.com/robbyrussell/oh-my-zsh.git $OH_MY_ZSH

platform=$(uname | awk '{print tolower($0)}')
[[ -f "setup_$platform" ]] && source "./setup_$platform"
