#!/bin/bash

brew install zsh
[[ ! $SHELL =~ "zsh" ]] && chsh -s `which zsh`

brew install pandoc
brew install ripgrep

# gnu tools better than osx defaults
brew install gawk
brew install gnutls
brew install gnu-sed
brew install gnu-tar
brew install coreutils
brew install gnu-indent

for f in ~/dotfiles/fonts/*; do source $f; done

# Add powerlevel10k to the list of Oh My Zsh themes.
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
# Restart Zsh.
exec zsh

# Configure powerlevel10k fonts
p10k configure