#!/bin/bash

brew install zsh
[[ ! $SHELL =~ "zsh" ]] && chsh -s `which zsh`

brew install pandoc
brew install ripgrep

# gnu tools better than osx defaults
brew install gawk --with-default-names
brew install gnutls --with-default-names
brew install gnu-sed --with-default-names
brew install gnu-tar --with-default-names
brew install coreutils --with-default-names
brew install gnu-indent --with-default-names

brew install caskroom/cask/brew-cask
brew cask install ngrok
brew cask install docker
brew cask install iterm2
brew cask install typora
brew cask install spectacle
brew cask install google-chrome

for f in ~/dotfiles/fonts/*; do source $f; done
