if [[ "$ZPROF" = true ]]; then
  zmodload zsh/zprof
fi

autoload -Uz compinit
compinit

export EDITOR='vim'
export VISUAL='vim'

export ZSH="$HOME/dotfiles/oh-my-zsh"

# Allows to source all the custom terminal config files on terminal load
for f in ~/dotfiles/zsh/*.sh; do source $f; done

# Allows to have a custom promp
DEFAULT_USER="laurentleclercpoulin"

# Add jump configurations (https://github.com/gsamokovarov/jump)
eval "$(jump shell)"

# Add direnv configurations
eval "$(direnv hook zsh)"

# Add pyenv-virtualenv configuration
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Allows oh-my-zsh to auto update itself without prompt
DISABLE_UPDATE_PROMPT=true

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel9k/powerlevel9k"

# Custom theme configurations see below to find the corresponding theme
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status rbenv)
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_MODE='awesome-fontconfig'

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  zsh-autosuggestions
)

# Enable oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Add custom syntax highlighting for zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

if [[ "$ZPROF" = true ]]; then
  zprof
fi
